- name: Install flask app with postgres database
  hosts: morjane-vm
  become: yes
  become_method: sudo
  remote_user: morjane

  tasks:

    - name: Install Git
      apt: name=git state=latest

    - name: Install flask ripository
      command: chdir=/home/morjane/ git clone https://github.com/RMorjane/simplon-devcloud-flask-ansible.git flask_app

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      
    - name: Install docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      shell: chmod +x /usr/local/bin/docker-compose
      shell: docker-compose --version

    - name: Install and execute flask app using docker-compose
      command: docker-compose up --build