- name: Install flask app with postgres database
  hosts: morjane-vm
  become: yes
  become_method: sudo
  gather_facts: yes
  remote_user: morjane

  tasks:

    - name: Install flask ripository
      shell: rm -Rf flask_app
      shell: chdir=/home/morjane/ git clone https://github.com/RMorjane/simplon-devcloud-flask-ansible.git flask_app

    - name: Go to the folder and execute docker-compose
      shell: chdir=/home/morjane/flask_app/ docker-compose up --build